name: flutter_link_previewer
description: Flutter Link Previewer
version: 0.2.0
homepage: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_chat_types: ^2.0.0
  flutter_linkify: ^5.0.0
  html: ^0.15.0
  http: ^0.13.0
  linkify: ^4.0.0
  meta: ^1.3.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
